language: node_js
sudo: false
before_script:
  - npm install web-component-tester
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
env:
  global:
    - secure: xg2AYZ0Lx7tdCQXeCexHV4Se/I2lOsa2ugEm3QvG2jX7cnZMd7w07jv3EH0sm9hYqG7G11NiL1rKHc57RRMSLyrq1UtDBSVmRx5Fx0WVt+TkqZoVHhc8xOO2TGJFnTlucXEipRL7B+A9rp1hFwZIs8lb+frv7NtjulzYytbQ2J6ng2JxZanSxqz/honh4Td9jCzx+xUMSYUgrwGzWqr913l27feSC4+zfE9MyqNhboOWew13CmQ1OClDIfMWatUX5HQ9xqw+7gbVqwJ1kMQoATTEoaqu3xJ7r980bnzheVPc0GEoWJOcb4J+iNqpCPGTFHGVT88CcYrtVfFL8RuOwBgOzy4f7hIbvAoXXp12sv4xFKMek2Tzo5qR1RSq0jm1W/aDkZJIMH9VZaUdfcn2P+rE87NI7Y9PiYEZP3mnM6H6LqR+JjuW1tymL6Qv8X9BuSFAtTqbHOKNiWQm8I2xuJPgLVJbpYC6r1//ik9iF43kjGkL+ckamVzks2yTQKqj+XpHNjIxoCVOPKUdFW51OCogx3hQjLrTnVi/f7mBQaYNexprV43S1kJLzJN0pvwoMD3ulWhXCCYlTujA7VeWExvt8QLphuRALlKCsz2PJqJ4nIsAveEzj+0OIKoxSxWOgBNVvGKM1szTSFpIcfR5Q0+BFPIO0pNT5FuI97BzOUQ=
    - secure: Q1UtnrlEUZCCuAhnPymq5CNbmLYsOy0AqK7mY+wqdqugnix4uQjVt5AgVj9+1MRiqDb43Ftb/bdIJO/HYizYcgODoqm2VSOMjPJURIR1dZyAMt/8Ua8Fn9QOyTCE7lOnr+n+XtjR8gpWLZf8jpdwBvuPPXr5aVz8ZByWH8rprRpiRqo435YFMRoa2zf1PhguKLxXKsyM9V/kdYy/WYQyLVpNdbyqCvj8czf9RryI0ZQ9ETjjAnGIDWefCjI2o01CJDx/5RYdtprEBslcyTw0gYwe9hfvnzDz7TKdBp8B3ssYthYG5rfxADIIQdBcKCJL+3KnoUJD8zMRNleMPWrqgCYPOuCQq+bV3qx/zlFa5ziQURTHMWAxJt1gFpqv4A5atlgefaLm+0KzQu/0MQV7PffCLAUe+l9MhtY9VbSpVMNvro1YteRwYX6x3bdDVq++fsTFBs3+xmvnOsEVIRYOWalUf2w6wVPi+bUfeTRM6cX2WpyyQ7QTVDJVA7CoQN/3GxnMp0wuL0/G2riEZcYONpzEGeqeHDFgLvbXR3+49SYw/zGf4pdDDB6+x+Wq57DcdwcY7hbmP5Ws2zyzqTaecbM40zypUb4XRsCo4ZTi27kGPzkchqUk0yxqUR5HZpKbpjQ8tpGl5O6qtT0L7eeD4BG2MWPVes0k8pVZ9OxFDyw=
node_js: 4
addons:
  firefox: '42.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
