# polymirage

Polymer in a jar.  Polymirage is nothing more than a jarfile resource
containing the Polymer library.

Motivation:

Polymer is heavily invested in the Javascript ecosystem; to intall it,
you have to install `node`, `npm`, `bower`, etc.  That's a lot of
installation and configuration of stuff a Clojure programmer usually
does not want or need to deal with.  Polymirage is intended to make
life slightly less horrible for Clojure/Clojurescript developers, who
can use it instead of going through the
link:https://www.polymer-project.org/1.0/docs/start/getting-the-code.html[Polymer
intallation rituals].

[NOTE]

The name of the library is polymirage rather than polymer, just to
avoid confusion.  But the files in the polymirage jar file start with
`polymer`, e.g. `polymer/iron-list/iron-list.html`.

## Usage

Leiningen dependency:

----
[polymirage "1.1.4"]
----

In a web app, the polymirage jar file is included in the classpath, so
you can use standard techniques for loading resources.

One easy way to do this is to "require" `[ring.middleware.resource
:refer [wrap-resource]]` and use it like so:

[source,clojure]
----
(ns myapp.core
  (:require [ring.middleware.resource :refer [wrap-resource]]
  ...)
  ...

(def app
  (-> app-routes
    (wrap-resource "/")))
----

This makes the polymer library available at the app root `/`.  Then
edit your HTML `<script src="...">` and `<link href="...">` to refer
correctly; for example, using hiccup:

[source,clojure]
----
    [:script {:src "polymer/webcomponentsjs/webcomponents-lite.js"}]
----

## License

The Polymer code in the jar:

Copyright (c) 2015 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
