= miraj
Webcomponents, the Clojure way

The goal of the Miraj project is to extend the Clojure language to
encompass web programming. That means, among other things, excising
the warts of HTML, Javascript, and CSS. The meta-programming
facilities of Clojure make it possible to present the programmer with
an idiomatic, 100% Clojure web programming experience, where the
conceptual and syntactic infelicities of HTML, Javascript, and CSS are
tucked away as implementation details. In much the same way that
Clojure itself hides the unpleasantness of Java, and treats dealing
with Java classes and objects as implementation details.

There are three parts to this. One is to provide seamless functional
support for HTML5. But it is not enough to provide a Clojure function
for each HTML element. That would allow us to compose the functions,
but the result would be higher-order _Clojure_ functions, not HTML
functions. To get first-class HTML functions, we also must to support
the emerging https://www.webcomponents.org/[webcomponents]
standards. Webcomponents make it possible to treat HTML as a
functional language in which HTML elements (functions) can be defined
and composed, passed as arguments and returned as values, etc. _in the
browser_.

IMPORTANT: The HTML "functions" in the Miraj libraries are better
thought of as co-functions. HTML functions run on the browser; what
Miraj provides is a collection of Clojure functions that are dual to
the HTML functions. Functions return values; co-functions have side-effects.

Miraj code -> Co-DOM (Clj data structure) ->(compile)-> HTML -> (send to browser) -> HTML ->(co-compile)-> DOM (Browser data structure)



NOTE: Currently only link:https://www.polymer-project.org/1.0/[Polymer] webcomponents are supported.


The third part: idiomatic clojure, replacing HTML weirdness (e.g. `<head>`).

== quickstart

Sugar:

[source,clojure]
----
(h/span :#foo.bar.baz!frob "hello") ; => <span id="foo" class="bar baz" frob>hello</span>
;; with miraj.style aliased to s:
(h/span {::s/color "red"} "hi")     ; => <span style="color:red;">hi</span>
(h/span :#foo {::s/hover {:color "red"}} "hi")
; => <span>hi</span><style>#foo:hover {color:red;}</style>
----

A page:

.src/clj/index.clj
[source,clojure]
----
(defpage
  "Hellow World demo"
  (:require [miraj.polymer.paper :as paper :refer [button card]])
  (:body
   (h1 "Hello, World!")
   (div :#cards
        (paper/card {:heading "Hello, you ol' Card!"}
                    (div :.card-content "Some content")
                    (div :.card-actions (paper/button :#btn!raised "Some action"))))))
----

.src/clj/index.cljs.edn
[source,clojure]
----
{:require  [index.core]}
----

.src/clj/index/deps.edn
[source,html]
----
{:imports [[assets hello-world]]}
----

.src/clj/index/core.cljs
[source,clojure]
----
(ns index.core)
(enable-console-print!)
(println "Hello World")
(let [btn (.getElementById js/document "btn")]
  (.addEventListener btn "click" (fn [_] (js/alert "Hello, World!"))))
----

./assets/hello-world.html
[source,assets/hello-world]
----
<style>
      h1 {text-align:center;}
      // etc.
</style>
<script>
handle_click = function(msg) {
    console.log("hey, " + msg + ", you clicked me!");
    alert("Hello World (from " + msg + ")!");
}
</script>
----


== namespaces and pagespaces

Miraj exploits the similarity between the `ns` macro of Clojure and
the `<head>` element of HTML. Just as the `:require` directive of `ns`
tells Clojure to find and load a Clojure resource, elements like
`<link>` and `<script>` contained in `<head>` tell the browser to find and load
resources.

By convention, a Clojure source file begins with an `ns` statement
that establishes a _namespace_ for the file. It also usually contains
a `:require` directive (for native Clojure resources) and sometimes an
`:import` directive (for foreign resources).

The markup libraries of the Miraj project - `miraj.html`,
`miraj.polymer.paper`, etc. - are designed to be listed in
`:require`. This tells Clojure to find and load them, which works
since they are ordinary Clojure libraries, But they will also be used
by the Miraj compiler to construct the HTML `<head>` element that will
do the same in the browser.

The Clojure namespace of a file that contains Miraj page definitions -
using `miraj.core/defpage` - does double-duty: it also serves as a
_pagespace_. At page compile time, the Miraj page compiler will treat
the namespace containing `defpage` definitions as a pagespace
containing resources needed for the page definitions. This includes,
in particular, the miraj libraries specified in the `:require`
directive of the `ns` declaration. The Miraj compiler will discover
the miraj libraries required, and use them to generate the `<link>`
elements needed for the `<head>` section of each page.

The key function for building webpages with Miraj is `defpage`.


== defpage

Note that miraj component libs are required just like any libs.

WARNING: Always use an alias. Use :refer for efficiency - without it,
all resources for the lib will be downloaded at runtime.

[source,clojure]
----
(ns simple.pages.goodbye
  (:require [miraj.core :as miraj]
            [miraj.co-dom :as codom]
            [miraj.html :as h]
	    ;; these two are component libraries; they will be used to construct <link> elements
            [miraj.polymer.paper :as paper :refer [button card]]
            [miraj.polymer.iron :as iron :refer [icon icons]]
  ...)
...
(miraj/defpage sayonara
  {:title "miraj demo"
   :description "This demonstrates usage of defpage."}
  (:body
   (h/h1 "GOODBYE MIRAJ!")
   (h/div (iron/icon {:icon "menu"}))
   (h/div ::cards     ;; <=  id="cards"
          (paper/card {:heading "Goodbye, you ol' Card!"}
                      (h/div {:class "card-content"} "Some content")
                      (h/div {:class "card-actions"}
                             (paper/button {:raised nil} "Some action"))))))
----

This compiles to:

[source,html]
----
<!doctype html>
<html>
    <head>
        <script type="text/javascript" src="/bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
        <meta name="description" content="this page demonstrates usage of miraj.html and polymer">
        <meta name="title" content="miraj goodbye demo">
        <link rel="import" href="/bower_components/paper-button/paper-button.html">
        <link rel="import" href="/bower_components/iron-icon/iron-icon.html">
        <link rel="import" href="/bower_components/iron-icons/iron-icons.html">
        <link rel="import" href="/bower_components/paper-card/paper-card.html">
    </head>
    <body>
        <h1>GOODBYE MIRAJ!</h1>
        <div>
            <iron-icon icon="menu"></iron-icon>
        </div>
        <div id="cards">
            <paper-card heading="Goodbye, you ol' Card!">
                <div class="card-content">Some content</div>
                <div class="card-actions">
                    <paper-button raised>Some action</paper-button>
                </div>
            </paper-card>
        </div>
    </body>
</html>
----

The syntax of `defpage` is: pagename, clojure docstring, metadata map
(optional), directives. `defpage` understands the following
directives:

* :import
* :css
* :js
* :preload  (i.e. <link rel='preload'...>)
* :body


== styling

CSS Styling options:

* inlined using `<style>` elements

* imported directly using `<link rel="stylesheet"...>` to retrieve a CSS
  file - one containing only CSS and no HTML - no `<style>` element

* imported indirectly using `<link rel="import"...>`, where the
  imported file is an HTML file containing a `<style>` element

* * imported indirectly using `<link rel="import"...>`, where the
  imported file is an HTML file containing style modules,
  i.e. `<dom-module>` elements containing `<style>` elements.

To use style modules in the main doc, you must link to it with
rel="import" and then refer to the styles in <style> elements using include="mystyle". you must also use is="custom-style"; e.g. `<style is="custom-style" include="foo">`

Miraj:

* `:css` directive on `defpage` supports inline CSS in the header; the
  ordinary `h/style` tag can be used in the :body.

* :css also supports direct importing, using a vector of import specs

* `:import` directive supports indirect HTML importing.

* :import with the :modules flag supports indirect importing of style modules



== dependencies

There are two kinds of dependencies involved in an HTML page, lexical
and non-lexical.  Lexical dependencies are web component libraries,
containing tags referred to by the HTML text; they are just like the
lexical dependencies listed in the `:require` and `:import` directives
of Clojure's `ns` form.  Non-lexical dependencies are the tradition
assets like CSS and Javascript files.

In principal, the program text of an HTML app should contain only HTML
and references to lexical dependencies, just as the text of a Clojure
program contains only Clojure text and references (via `:require` and
`:import`) to lexical dependencies.  External dependencies should be
specified separately as part of the buld structure.  Miraj uses a
`deps.edn` file to support this structuring strategy. It also supports
the more traditional direct embedding strategy using directives like
`:css` (see below).

== deps.edn

Dependencies for page `foo/bar.clj` listed in `foo/bar/deps.edn` will
be written to `foo/bar/deps.html` and included in `foo/bar.html` using
an HTML import.  This separates lexical and non-lexical dependencies
and minimizes the number of `<link>` and `<script>` tags used in the
page.

NOTE: A Clojure namespace may contain more than one `defpage`.  In
this case, use the defpage var name to form the deps.edn path.  For
example, if `foo/bar.clj` contains `defpage index`, the var will be
`foo.bar/index`, generating `/foo/bar/index.html` so the deps file
should be `foo/bar/index/deps.clj`.  If it contains a "lambda"
defpage, the deps file should be `foo/bar/deps.edn`.


The `deps.edn` file supports the following directives:


===== :imports

The syntax of this directive is similar to the syntax of Clojure's
`require`: a dotted namespace followed by a list of elements in the
namespace.  But here the "elements" in the (filesystem) namespace are
treated as HTML files.  For example:

[source,clojure]
----
[foo.bar a b]  =>  /foo/bar/a.html, /foo/bar/b.html
----

You can include any html in an HTML import file, so you can put both
`<style>` and `<script>` elements in one import file, for example.

[source,clojure]
----
{:import [[foo.bar baz buz]]}
=>
<link rel="import" href="/foo/bar/baz.html">
<link rel="import" href="/foo/bar/buz.html">
----


===== :styles

The `:styles` directive is similar to the `:import` directive, but it
adds some special logic to support Polymer's "style modules" (see
https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-modules[Use
style modules]).

The syntax of this directive bears several possible interpretations.  For
example `[foo.bar a b]` may be interpreted as:

1. `foo/bar/a.css`, `foo/bar/b.css`
2. `foo/bar.html`, containing modules `a` and `b`

Miraj will try these in order.

NOTE: If you want to put your CSS in an HTML file without using
modules, use `:imports` rather than `:styles`.

For example:

./styles/demo.html
[source,html]
----
<dom-module id="foo">
  <template>
    <style >
    ...
    </style>
  </template>
</dom-module>

<dom-module id="bar">
  <template>
    <style >
    ...
    </style>
  </template>
</dom-module>

----

.deps.edn
[source,clojure]
----
(:styles [[styles.demo foo bar]])
==>
<link rel="import" href="/styles/demo.html">
<custom-style>
   <style include="foo"></style>
   <style include="bar"></style>
</custom-style>
----

WARNING: FIXME: test custom-styles for main doc


==== Examples:

.sweetest/deps.edn
[source,clojure]
----
{;; clojure-style (namespaces)
 :styles  [[styles.demo foo bar]] ;; /styles.demo.html, modules=foo, bar
 :scripts  [foo.bar a b]  ;; /foo/bar/a.js, /foo/bar/b.js
 :imports [[foo.bar baz buz]] ;; /foo/bar/baz.html, /foo/bar/buz.html
 ;; traditional (paths)
 :js ["/js/custom-elements.min.js" "foo/bar.js"]
:styles [css.sweetest]

 :icons [[miraj.polymer.iron communication hardware iron social]
         [miraj.vaadin vaadin]]
 ;; :miraj.polymer/icons [[miraj.polymer.iron communication hardware iron social]]
 ;; :miraj.polymer/icons [[iron communication hardware iron social]
 ;;                       [miraj.vaadin]]
 :miraj.polymer/styles [[miraj.polymer.iron.styles demo flex-mixins]
                        [miraj.polymer.paper.styles color typography]]}


----


== embedded dependency references

However, for a more traditional structure, miraj also supports direct
embedding of dependency references, using `:css`, `:js` and `:link`
directives.

Dependencies listed using directives like :css or :js will be included
in the <head> element of the generated HTML.


==== html5 imports

The new https://w3c.github.io/webcomponents/spec/imports/[HTML
Imports] standard provides a uniform mechanism for importing any kind
of asset into an HTML page. Instead of stuffing a bunch of `<link>`
and `<stylesheet>` elements the `<head>` element of our webpage, we
can put them into an HTML file and then import that file.


Miraj supports this in the form of the an `:import` directive on the
`defpage` macro. There are two ways to use it. For remote assets you
may use a map as show further below.  But if the assets you wish to import
are local, you can use the same syntax as used by the `:import`
directive of `clojure.core/ns`:

[source,clojure]
----
(miraj/defpage hello
  "Styled version of hello webpage."
  {:title "Miraj demo: importing assets"
   :description "this page demonstrates usage of :import in a defpage"}
  (:import [[styles.hello button card]
            [styles.simple fonts]])
 ...)
----

At compile time, this will result in the insertion if the following in
the `<head>` element of the page:

[source,clojure]
----
<link rel="import" href="/styles/hello/button">
<link rel="import" href="/styles/hello/card">
<link rel="import" href="/styles/simple/fonts">
----

The compile operation will also check to make sure these resources are
accessible; it is the programmer's responsibility to provide them.

You can also import third-party assets. Instead of using the vector
 format above, you can use a map. Miraj supports all the attributes of
 link. You can write (for example):

[source,clojure]
----
  (:import [{:href "https://unpkg.com/purecss@0.6.2/build/pure-min.css"
	        :integrity "sha384-UQiGfs9ICog+LwheBSRCt1o5cbyKIHbwjWscjemyBMT9YCUMZffs6UqUTd0hObXD"
	        :crossorigin "anonymous"}])
----

==== traditional (direct) imports.

Miraj also supports the traditional method of directly importing
external stylesheets and scripts using the `<link
rel="stylesheet"...>` and `<script>` tags.  The miraj way is to use
`:css` and `:js` directives.   As with `:import`, there
are two ways to do it.

[source,clojure]
----
(miraj/defpage hello
  "Styled version of hello webpage."
  {:title "Miraj demo: inlining assets"
   :description "this page demonstrates usage of :import in a defpage"}
  (:css [[css.stylesheets foo bar]])
  (:js  [[js.scripts baz buz]])
  ")
...)
----

At compile time the following will be inserted into `<head>`:

[source,html]
----
<link rel="stylesheet" type="text/css" href="/css/stylesheets/foo">
<link rel="stylesheet" type="text/css" href="/css/stylesheets/bar">
<script type="text/javascript" src="/js/scripts/baz"></script>
<script type="text/javascript" src="/js/scripts/buz"></script>
----

NOTE: The `type` attributes may be removed by using `miraj.core/optimize`.

You can also use maps, and you can combine vector and map specs:

[source,clojure]
----
  (:css [{:href "https://unpkg.com/purecss@0.6.2/build/pure-min.css"
          :integrity "sha384-UQiGfs9ICog+LwheBSRCt1o5cbyKIHbwjWscjemyBMT9YCUMZffs6UqUTd0hObXD"
          :crossorigin "anonymous"}
         [styles.css button card.css]
         {:href "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"}])

----

=== inline

Miraj also supports inline CSS (`<style>` tag) and Javascript
(`<script>` tag). To inline CSS or Javascript code in the `<head>`
element, use the `:css`, resp. `:js` directive, just as you would for
a traditional direct import. The only difference is that you pass a
string rather than a vector of specs.

Of course you can always inline javascript in attributes too.

[source,clojure]
----
(miraj/defpage hello
  "Styled version of hello webpage."
  {:title "Miraj demo: inlining assets"
   :description "this page demonstrates inlined css and js."}
  (:css "body{font-size:16px}")
  (:js "
    function functionOne() { alert('You clicked me'); }
  ")
   ...
   (h/a {:href "#" :onClick "functionOne();"} "Click Me")
 ...)
----

NOTE: You can put Javascript in the header; `miraj.core/optimize` will
automatically move it to the end of the document.


== special ops (miraj.co-dom)

* binding annotations

[source,clojure]
----
(h/div :foo)                ; =>  <div>{{foo}}</div>
(h/div 'foo)                ; =>  <div>[[foo]]</div>

(h/div {:foo :bar} "hi") ; => <div foo="{{bar}}">hi</div>
(h/div {:foo 'bar} "hi") ; => <div foo="[[bar]]">hi</div>
----

* id, class attribs

[source,clojure]
----
(h/div :#foo)               ; =>  <div id="foo"></div>
(h/div :.foo)              ; =>  <div class="foo"></div>
(h/div :#foo.bar)           ; =>  <div id="foo" class="bar"></div>
----

* boolean attributes

[source,clojure]
----
(h/div :!foo)          ; =>  <div foo></div>
(h/div {:foo ""})           ; =>  <div foo></div>
(h/div {:foo "foo"})        ; =>  <div foo></div>
;; todo:
(h/div :!foo "hi")          ; =>  <div foo>hi</div>
(h/div "hi" :!foo " there") ; =>  <div foo>hi there</div>
(h/div "hi" :!foo)          ; =>  <div foo>hi</div>
----

* style attribs

[source,clojure]
----
;; (:require [miraj.style :as s])
(h/span {::s/color "red"} "hello") ;=> <span style="color:red;">hello</span>
----

= workflow

* if you're working a page (e.g. `defpage hello` in  `work/pages/styled/externals.clj`) in
  the repl, try something like this in a separate test file:

[source,clojure]
----
(ns work-test
  (:require [miraj.core :as miraj]
            [miraj.compiler :as wc]
            [miraj.co-dom :as x]))
(do
  (require '[work.pages.styled.externals :as pagespace] :reload)

  (->> #'pagespace/hello
       miraj/normalize
       miraj/optimize
       (x/pprint :html)))
----

Then evaluate the `do` clause whenever the code in
`work/pages/styled/externals.clj` changes.

* If you want to hot-reload your pages in a browser, run a server and
then run a monitor task in your webpage project.  If your app contains
multiple pages, you can work on one at a time by using the
--webpage-var parameter (or the --namespace param) of the
`boot-miraj/compile` task in your `boot monitor` pipeline. Then when
you make a change only that page will be recompiled.


== polyfills

For HTML imports on FF etc. use https://github.com/webcomponents/custom-elements


= troubleshooting

* You get ClassNotFoundException when you run boot-miraj/compile with
-w or -n. This may mean that in your boot.build you are passing a
namespace or fully qualified var without quoting it.


= Webservers

== HTTP

* link:http://java-source.net/open-source/web-servers[Open Source Web Servers in Java] - nice list

* link:http://www.eclipse.org/jetty/[Jetty]

* link:http://webbitserver.org/[Webbit]

* link:http://pygmy-httpd.sourceforge.net/[pygmy]

* link:http://simpleweb.sourceforge.net/index.php[Simple]

* link:https://github.com/tinspin/rupy[rupy]

* link:http://winstone.sourceforge.net/[winstone]

== Serlvet

Jetty, Simple, Tomcat, Winstone


## License

The Polymer code in the jar:

Copyright (c) 2015 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
