language: node_js
sudo: false
before_script:
  - npm install web-component-tester
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
env:
  global:
    - secure: EbNQJATlfP5xdbnxnhdBC7T6q86TaZhZoqucx12wn88AiTe24lEB6b+Vd9ZwELi4B0G8qrQWIXoGLNCYZg6tn8+k9uJgE9kH+YvZLlM6HmHZ9HcuMjNg2ugsYJW9WuY6N5om0YvadZWl2nJECk9cX+KXE9Rq1HTUy3r+tXj0ezw=
    - secure: A0ZrObu71lLS2r7RIeFxLoveGoQ4bheNMOusNXfsHrZLlnwKJQ5tDcc6ZCipGfIPeIJPAR+Gdo+UVKB13q47rYkBRljgy7Mr3RXefiJKANJiSLfUgAPXLSaFQTk1ghvD+hHQiM/hGmWY/J9iranShsRzYMHq2ZY4edxdTzknijk=
node_js: 4
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
