
A co-function is a routine whose input is externally observed behavior
and whose output is externally observable behavior.

Making a clean distinction between state and behavior means we can use
functions to implement co-functions.  It's all a matter of perspective.

For example, to handle a GET request, a web server uses a co-routine.
The incoming request is client behavior observed by the server, and
the outgoing response is server behavior observable by the client.
The incoming request arrives from outside; before the server can route
it to a handler function, it must observe it.  Having done so, it
analyzes it and routes it to a handler.  The handler, too, must
observe this input before it can compute; in most cases "routing the
request to a handler" means making an internal function call, but it
could mean sending the request to another server.  In any case, once
the handler is finished it produces a response that is sent to the
client - exhibited as server behavior for client observation.  Again,
the normal case is that the handler returns its response to the
webserver, whose job it is to send it to the client.

= function, algorithm, program

* mathematical function: well-known

* algorithm: adds logic to mathematics; computational representation
  of a mathematical function.

* program: a text in a programming language designed to be executed by
  a machine.  Algorithms are abstract; programs are concrete.

So-called functions in programming languages are not really functions;
rather, they are computational (algorithmic) approximations of
mathematical functions.

So we say e.g. a function is a program (routine) that ...

